delete
from person
where id > 0;

SELECT *
FROM person;

DROP TABLE person;

CREATE TABLE person
(
    id    INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(200),
    age   INT CHECK ( age > 0 and  age < 130),
    email VARCHAR UNIQUE ,
    address VARCHAR
);

INSERT INTO person(name, age, email, address)
VALUES ('Tom', 33, 'tom@gmail.com', 'Belarus, Baranovichy, 123456'),
        ('Kate', 18, 'Kate@ya.ru', 'Belarus, Minsk, 222222'),
        ('Sergey', 34, 'Sergey@ya.ru', 'Russia, Moscow, 333333');


CREATE TABLE IF NOT EXISTS Item
(
    id        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id INT          REFERENCES Person (id) ON DELETE SET NULL,
    item_name VARCHAR(100) NOT NULL
);

INSERT INTO Item(person_id, item_name)
VALUES (1, 'Book'),
       (1, 'AirPods'),
       (2, 'Iphone'),
       (3, 'Kindle'),
       (3, 'TV'),
       (3, 'PlayStation');