delete
from person
where id > 0;

SELECT *
FROM person;

DROP TABLE person;

CREATE TABLE person
(
    id    int GENERATED BY DEFAULT AS IDENTITY,
    name  varchar,
    age   int,
    email varchar
);

CREATE TABLE person
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar NOT NULL,
    age   int check ( age > 0),
    email varchar UNIQUE
);

INSERT INTO person(name, age, email)
VALUES ('Tom', 33, 'tom@gmail.com');
INSERT INTO person(name, age, email)
VALUES ('Kate', 18, 'Kate@ya.ru');
INSERT INTO person(name, age, email)
VALUES ('Vitaliy', 33, 'Vitaliy@gmail.com');


ALTER TABLE person 
    ADD COLUMN address varchar NOT NULL DEFAULT '---';

INSERT INTO person(name, age, email, address)
VALUES ('Виталий', 33, 'tom@gmail.com', 'Belarus, Baranovichy, 123456');