-- Person

DROP TABLE IF EXISTS Person;

CREATE TABLE IF NOT EXISTS Person
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    age  INT CHECK ( age < 120 )
);

INSERT INTO Person(name, age)
VALUES ('Top', 35),
       ('Bob', 52),
       ('Kate', 14);

SELECT *
FROM Person;

-- Item

DROP TABLE IF EXISTS Item;

CREATE TABLE IF NOT EXISTS Item
(
    id        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id INT          REFERENCES Person (id) ON DELETE SET NULL,
    item_name VARCHAR(100) NOT NULL
);

INSERT INTO Item(person_id, item_name) VALUES
    (1, 'Book'),
    (1, 'AirPods'),
    (2, 'Iphone'),
    (3, 'Kindle'),
    (3, 'TV'),
    (3, 'PlayStation');

SELECT *
FROM Item;